spring.application.name=NoBroker

spring.datasource.url=jdbc:postgresql://localhost:5432/NoBroker
spring.datasource.username=postgres
spring.datasource.password=1234567890
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
